### ISSUE TITLE
Snake and ladders(sal) not stopping.

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/seasonalbot#252] opened 2019-08-08 14:56 UTC
Recently encountered an error with the sal game where the game would not respond to any reaction, its been running and cannot be stopped due to some reason.

## Steps to Reproduce
possible fix:
- Make a timer after which the game shuts down automatically due to inactivity.

## Other
Comment if you got any any other ideas for this fix.

**Comment by sco1** [comment] 2019-08-08 14:57
The permissions for ending the game should be expanded to moderation staff rather than locked to the person who started the game.

**Comment by SebastiaanZ** [comment] 2019-08-08 15:03
I agree that's a good idea.

In this case, the game became totally unresponsive, though. The member that originally started the game couldn't/can't get it to stop either, so this probably won't fix this specific problem.

Another alternative is to have it check how old the "already running" game is and, if it's older than an hour (or something), discard the old game and start a new game anyway.

**Comment by sco1** [comment] 2019-08-08 15:09
Looking at the source, the game should be getting cancelled if nobody reacts (or the game doesn't start) after 5 minutes, but the timeout exception handling likely isn't correct:

https://github.com/python-discord/seasonalbot/blob/e906696dbc880f283146cb04aa8916f04f8ab545/bot/seasons/evergreen/snakes/utils.py#L464-L467

**Comment by SebastiaanZ** [comment] 2019-08-08 15:10
The problem is line 466, it should be:

```py
await self.cancel_game(self.author) 
```

From the logs:
```
pydis/seasonalbot/bot/seasons/evergreen/snakes/utils.py:466: RuntimeWarning: coroutine 'SnakeAndLaddersGame.cancel_game' was never awaited
  self.cancel_game(self.author)
```

**Comment by sco1** [comment] 2019-09-04 11:08
Hi @RohanJnr, what’s the status of this fix? Are you still working on it or should we reassign?

**Comment by RohanJnr** [comment] 2019-09-04 15:10
Probably reassign, sorry :(

**Closed** 2019-09-11 04:34 UTC
Labels: approved, beginner, bug, refinement, work in progress
