### ISSUE TITLE
.roll appears to only resolve to emojis some of the time

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/seasonalbot#232] opened 2019-07-03 10:05 UTC
# Problem description
Some of the time when you do `.roll`, it will only show the emoji name, like `:terning6:` instead of the emoji itself. Reproduce this problem locally and see if you can figure out why this happens. Is it a Discord problem or is there anything we can change in the code to make this more consistent?

# Repro steps
Just do `.roll 6` a bunch of times, some of them will fail.

![image](https://user-images.githubusercontent.com/2098517/60583158-91e0fe80-9d8a-11e9-90c8-9298d0617fa0.png)

**Comment by SebastiaanZ** [comment] 2019-07-03 10:40
The problem is that we removed :terning4: a while ago and then added it back.

The id in the constants is still the id of the old, removed emoji, not the new one. I'll fix that.

**Comment by SebastiaanZ** [comment] 2019-07-03 11:03
This was fixed by changing the emoji id to the correct one.

**Closed by SebastiaanZ** 2019-07-03 11:03 UTC
Labels: bug, refinement, season - evergreen
